"""ذخیره‌سازی خودکار کشفیات در فرمت‌های مختلف."""
import os
import json
import csv
from datetime import datetime


RESULTS_DIR = "results"
LOG_FILE = os.path.join(RESULTS_DIR, "log.csv")


def _ensure_dir():
    os.makedirs(RESULTS_DIR, exist_ok=True)


def _timestamp():
    return datetime.now().strftime("%Y%m%d_%H%M%S")


def _safe_name(path):
    base = os.path.basename(path)
    name, _ = os.path.splitext(base)
    return name


def save_equations(input_file, n, d, n_eq, equations_orig,
                    equations_normalized, mu, sigma, singular_values,
                    denoise_info=None, max_degree=None):
    """
    ذخیره‌ی یک اجرا در سه فایل: txt، tex، json + افزودن به log.csv
    خروجی: dict با مسیرهای فایل‌های ساخته‌شده
    """
    _ensure_dir()
    base = _safe_name(input_file)
    ts = _timestamp()
    stem = f"{base}_{ts}"

    txt_path = os.path.join(RESULTS_DIR, f"{stem}.txt")
    tex_path = os.path.join(RESULTS_DIR, f"{stem}.tex")
    json_path = os.path.join(RESULTS_DIR, f"{stem}.json")

    # --- TXT ---
    with open(txt_path, "w", encoding="utf-8") as f:
        f.write("=" * 60 + "\n")
        f.write(f"کشف فرمول ریاضی — {input_file}\n")
        f.write("=" * 60 + "\n\n")
        f.write(f"زمان اجرا: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"بعد محیطی (n): {n}\n")
        f.write(f"بعد ذاتی (d): {d}\n")
        f.write(f"تعداد معادلات: {n_eq}\n")
        if max_degree is not None:
            f.write(f"درجه کتابخانه: {max_degree}\n")
        if denoise_info:
            f.write(f"سیگما نسبی قبل از حذف نویز: {denoise_info.get('sigma_rel', 0):.4f}\n")
            if denoise_info.get("denoised"):
                f.write(f"حذف نویز انجام شد (d = {denoise_info.get('d')})\n")
                sa = denoise_info.get("sigma_after", 0)
                f.write(f"سیگما پس از حذف نویز: {sa:.4f}\n")
            else:
                f.write("نویز ناچیز بود.\n")
        f.write("\n" + "-" * 60 + "\n")
        f.write("معادلات در مختصات اصلی:\n")
        f.write("-" * 60 + "\n")
        for i, eq in enumerate(equations_orig, 1):
            f.write(f"  G{i} = {eq} = 0\n")
        f.write("\n" + "-" * 60 + "\n")
        f.write("معادلات در مختصات نرمال‌شده:\n")
        f.write("-" * 60 + "\n")
        for i, eq in enumerate(equations_normalized, 1):
            f.write(f"  F{i} = {eq} = 0\n")
        f.write("\n" + "-" * 60 + "\n")
        f.write("پارامترهای نرمال‌سازی:\n")
        f.write("-" * 60 + "\n")
        f.write(f"  میانگین: {list(mu)}\n")
        f.write(f"  انحراف معیار: {list(sigma)}\n")
        f.write("\n" + "-" * 60 + "\n")
        f.write("مقادیر تکین (۱۰ تای اول):\n")
        f.write("-" * 60 + "\n")
        if len(singular_values) > 0:
            for i, s in enumerate(singular_values[:10], 1):
                f.write(f"  s{i} = {s:.6f}\n")
        f.write("\n" + "=" * 60 + "\n")

    # --- TEX ---
    with open(tex_path, "w", encoding="utf-8") as f:
        f.write("% Auto-generated by mathbot\n")
        f.write(f"% Input: {input_file}\n")
        f.write(f"% Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"% Ambient dim n = {n}, intrinsic dim d = {d}\n\n")
        f.write("\\begin{align}\n")
        for i, eq in enumerate(equations_orig, 1):
            latex = _sympy_to_latex(eq)
            f.write(f"  G_{{{i}}} &: {latex} = 0")
            if i < len(equations_orig):
                f.write(" \\\\\n")
            else:
                f.write("\n")
        f.write("\\end{align}\n")

    # --- JSON ---
    data = {
        "input_file": input_file,
        "timestamp": datetime.now().isoformat(),
        "ambient_dim": int(n),
        "intrinsic_dim": int(d),
        "n_equations": int(n_eq),
        "max_degree": max_degree,
        "equations_original": [str(eq) for eq in equations_orig],
        "equations_normalized": [str(eq) for eq in equations_normalized],
        "mu": [float(x) for x in mu],
        "sigma": [float(x) for x in sigma],
        "singular_values_top10": [float(s) for s in singular_values[:10]],
        "denoise_info": {
            k: (float(v) if isinstance(v, (int, float)) else v)
            for k, v in (denoise_info or {}).items()
        },
    }
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    # --- LOG ---
    header = ["timestamp", "input_file", "n", "d", "n_eq",
              "n_equations_found", "max_degree", "denoised",
              "sigma_rel_before", "txt_file"]
    file_exists = os.path.exists(LOG_FILE)
    with open(LOG_FILE, "a", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        if not file_exists:
            writer.writerow(header)
        writer.writerow([
            datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            input_file, n, d, n_eq,
            len(equations_orig),
            max_degree if max_degree is not None else "",
            bool(denoise_info and denoise_info.get("denoised")),
            f"{(denoise_info or {}).get('sigma_rel', 0):.4f}",
            os.path.basename(txt_path),
        ])

    return {
        "txt": txt_path,
        "tex": tex_path,
        "json": json_path,
        "log": LOG_FILE,
    }


def _sympy_to_latex(expr):
    """تبدیل sympy expression به LaTeX."""
    try:
        import sympy as sp
        return sp.latex(expr)
    except Exception:
        return str(expr)


def list_discoveries():
    """فهرست همه‌ی کشفیات ذخیره‌شده."""
    _ensure_dir()
    files = sorted(os.listdir(RESULTS_DIR))
    txt_files = [f for f in files if f.endswith(".txt")]
    return txt_files
